name: Test and Release

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-central-1
  STACK_BASE_NAME: bddfrawsx-${{ github.sha }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Build
        run: npx tsc
      - name: Lint
        run: npm run lint
      - name: Set up test resources
        run: npx cdk deploy --require-approval never
      - name: Test
        run: npm test
      - name: Semantic release
        if: success()
        continue-on-error: true
        run: |
          npm i --no-save semantic-release@next
          npx semantic-release
      - name: Clean up End-to-End test resources
        if: always()
        run: npx cdk destroy -f
